name: macOS VNC Full Setup
on:
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab

jobs:
  build:
    name: Start macOS VNC Session
    runs-on: macos-latest

    steps:
      - name: Setup VNC and Start Ngrok Tunnel
        env:
          NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
          USER_NAME: "Sx_developer" # You can change the username here
        run: |
          # --- Generate a random, secure password ---
          VNC_PASSWORD=$(openssl rand -base64 12)
          echo "VNC Password for this session is: $VNC_PASSWORD"

          # --- Create the user account ---
          echo "Creating user account: $USER_NAME"
          sudo dscl . -create /Users/$USER_NAME
          sudo dscl . -create /Users/$USER_NAME UserShell /bin/bash
          sudo dscl . -create /Users/$USER_NAME RealName $USER_NAME
          sudo dscl . -create /Users/$USER_NAME UniqueID 1001
          sudo dscl . -create /Users/$USER_NAME PrimaryGroupID 80
          sudo dscl . -create /Users/$USER_NAME NFSHomeDirectory /Users/$USER_NAME
          sudo dscl . -passwd /Users/$USER_NAME "$VNC_PASSWORD"
          sudo dscl . -append /Groups/admin GroupMembership $USER_NAME

          # --- Enable and configure macOS Screen Sharing (VNC) ---
          echo "Enabling VNC Server..."
          sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart -configure -allowAccessFor -allUsers -privs -all
          sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart -configure -clientopts -setvnclegacy -vnclegacy yes
          
          # --- Set the VNC password ---
          sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart -configure -clientopts -setvncpw -vncpw "$VNC_PASSWORD"
          
          # --- Restart the VNC service to apply all settings ---
          sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart -restart -agent

          # --- Install and configure Ngrok ---
          echo "Starting Ngrok tunnel..."
          brew install ngrok
          ngrok authtoken $NGROK_AUTH_TOKEN
          ngrok tcp 5900 & # 5900 is the default VNC port

          # --- Wait for Ngrok to start and output the connection details ---
          sleep 10
          VNC_URL=$(curl -s http://127.0.0.1:4040/api/tunnels | jq -r '.tunnels[0].public_url')

          echo "✅✅✅ SETUP COMPLETE ✅✅✅"
          echo "-----------------------------------------------------"
          echo "Connect to this VNC address: ${VNC_URL}"
          echo "Username: ${USER_NAME}"
          echo "Password: ${VNC_PASSWORD}"
          echo "-----------------------------------------------------"

      - name: Keep Workflow Running (for debugging via tmate)
        uses: mxschmitt/action-tmate@v3

